export enum Family {
	SOLANACEAE = 'SOLANACEAE',
	CUCURBITACEAE = 'CUCURBITACEAE',
	BRASSICACEAE = 'BRASSICACEAE',
	FABACEAE = 'FABACEAE',
	POACEAE = 'POACEAE',
	APIACEAE = 'APIACEAE',
	LILIACEAE = 'LILIACEAE',
	ASTERACEAE = 'ASTERACEAE',
	CHENOPODIACEAE = 'CHENOPODIACEAE'
}